// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbuEokpuNEVxzeWDMzW3gmz0P6rYUWRuM',
    appId: '1:810311399809:web:521110ded4d313d7bc1080',
    messagingSenderId: '810311399809',
    projectId: 'flutterfirebase-45976',
    authDomain: 'flutterfirebase-45976.firebaseapp.com',
    storageBucket: 'flutterfirebase-45976.firebasestorage.app',
    measurementId: 'G-VRNLLHXJR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_hqcM5nX4KpTzxeskeG4yk0OJSnIayo',
    appId: '1:810311399809:android:f7d5bd9a9e8f7eb8bc1080',
    messagingSenderId: '810311399809',
    projectId: 'flutterfirebase-45976',
    storageBucket: 'flutterfirebase-45976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDZifIZsvFTfTWx5l3RXpqcsJn3uLe73Y',
    appId: '1:810311399809:ios:48edb75f590a58babc1080',
    messagingSenderId: '810311399809',
    projectId: 'flutterfirebase-45976',
    storageBucket: 'flutterfirebase-45976.firebasestorage.app',
    iosClientId: '810311399809-oc1ak7sh3phjvbouec5474jvt6eun3c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDZifIZsvFTfTWx5l3RXpqcsJn3uLe73Y',
    appId: '1:810311399809:ios:48edb75f590a58babc1080',
    messagingSenderId: '810311399809',
    projectId: 'flutterfirebase-45976',
    storageBucket: 'flutterfirebase-45976.firebasestorage.app',
    iosClientId: '810311399809-oc1ak7sh3phjvbouec5474jvt6eun3c4.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbuEokpuNEVxzeWDMzW3gmz0P6rYUWRuM',
    appId: '1:810311399809:web:6026d02d2d64c55bbc1080',
    messagingSenderId: '810311399809',
    projectId: 'flutterfirebase-45976',
    authDomain: 'flutterfirebase-45976.firebaseapp.com',
    storageBucket: 'flutterfirebase-45976.firebasestorage.app',
    measurementId: 'G-G16NY42K2P',
  );
}
